version: "3"

services:
  portero:
    build: .
    
    container_name: portero

    networks:
      - portero_net

    restart: unless-stopped
  
  db:
    container_name: portero-db
    image: postgres
    restart: unless-stopped
    networks:
      - portero_net
    environment:
      - POSTGRES_PASSWORD=root
  
networks:
  portero_net: